sequencing units:
  # Assumes that input reads are named like sequencing-unit.{I,R}{1,2}.fastq.gz
  # Use a descriptive name here and if you do not want to rename the original
  # files you can make a symbolic link in the data/reads folder that conforms
  # with the required naming.
  - nextseq

params:
  scATAC: "\
    -b data/barcodes/ \
    -g /shared_data/data/Mus_musculus_UCSC_mm10/Bowtie2Index/genome \
    -d 2 \
    -m 10"
  snATAC pre: "-t 5 -m 30 -f 2000 -e 75"
  bwa mem: "/shared_data/data/Mus_musculus_UCSC_mm10/BWAIndex/genome"
  macs2 callpeak: "-f BED -g mm -p 0.05 --nomodel --shift 150 --keep-dup all --outdir results/"

threads:
  scATAC: 8
  snATAC pre: 8
  bwa mem: 4